# Generated by Django 3.2 on 2024-01-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=120)),
                ('sage', models.IntegerField(default=18)),
                ('sbranch', models.CharField(choices=[('3', '-- Select Branch --'), ('0', 'Computer Science and Engineering'), ('1', 'AIML'), ('2', 'Others')], default='3', max_length=5)),
            ],
        ),
    ]
